### ISSUE TITLE
Markup Review by Paul Jackson

### ISSUE THREAD

**Issue by sylus** [wet-boew/wet-boew-drupal#253]
@pjackson28 did a quick review today of some things that need to be fixed in the distribution. I will be working pretty much exclusively on these improvements over the weekend. (Fences module will finally get some use!)

---

Thanks Will. I noticed there are a several HTML validation errors so those should be corrected. I also noticed you are using outdated metadata so you should align with what WET uses as it represents the latest recommendations form the IM policy centre.

I noticed how you are using the menu bar and I think UXWG is going to raise that as an issue. Those types of links shouldn't be in the menu bar, those are more appropriate in the site footer. "Contact Us" and "canada.gc.ca" are already duplicating what's in the site footer and "Home" will be duplicating what's in the breadcrumb. "Help" and "Search" should also be in the site footer (although normally the pattern is you do the initial search through the simple search on the right then have the option of doing a more advanced search on the search results page). If you don't have anything to put in the menu bar/mega menu, I recommend replicating the placeholder content used in the WET working examples.

Could you also change wet.openplus.ca into a landing page with links to all the examples you currently have in place? It would be a lot easier for the testers if you make it explicit what there is to test. Best way to do that is to list all the links in the content area like we do on the working examples page.

I also noticed a few other things:
- Mobile view (width < 768px) is badly broken. The header and footer are displaying incorrectly. Nothing seems to be working which is a big concern.
- You seem to be loading jQuery UI which could be problematic for mobile users. We decided to drop jQuery UI support because of the huge downloads and poor support for mobile devices. We also found no need for it as it duplicated native HTML5 technology or we already have more lightweight solutions in WET. We decided to go with the HTML5 polyfill approach rather than large scale and heavyweight alternative like jQuery UI.
- You have a lot of HTTP requests and large download sizes in comparison to WET core so performance is a concern. Here is a side-by-side comparison:
      - HTTP transfers: WET core: 26, Drupal variant: 39 (50% increase)
      - Download size: WET core: 219.2kb, Drupal variant: 442.1kb (102% increase)
      - Loading time: WET core: 1.45s (onload 2.91s), Drupal variant: 3.26s (onload: 3.13s) (125% increase) These numbers are concerning with regards to mobile support as a 50% incr
- The HTML files have a lot of white space and long file names and such. This could easily run into mobile caching issues down the road. The HTML file of the simple home page you have is 26.2kb in size where the same HTML file in WET core is 11.3kb (132% increase). iOS 3.1 HTML caching limit is 25.6kb while iOS 4 is 50kb (later versions of iOS 4 upped it to 100kb).

**Comment by sylus** [comment]
@openplus @mgifford @joel-osc @joejoseph00 @StephenOTT @eleclerc (also including @patcon but don't expect you to volunteer time but just in case! lol)

Will likely need help from you guys on this as release date is fast approaching.

Also keep in mind the full review will be happening early next week and I expect tons of other issues to pop up. As per last time these will likely be tons of minor fixes but will definitely need help! :)

**Comment by sylus** [comment]
Also the w3c html5 validator returned 23 errors and 2 warnings at: http://validator.w3.org/check?uri=http%3A%2F%2Fwet.openplus.ca%2F&charset=%28detect+automatically%29&doctype=Inline&ss=1&group=0&user-agent=W3C_Validator%2F1.3

Most of them are metatags related and it seems WET has their own government preferred standard for them so I will port the module I am using now and make it reflect the new standards.

I committed to @pjackson28 to have the validator return no errors or warnings, and make some headway on his other feedback for Monday.

**Comment by mgifford** [comment]
The W3C validator still doesn't do a very good job when you're combining HTML5, RDFa or any other metadata.  Mind you there's definitely a few code issues that need to be cleaned up.

There's still that problem with "Customize your search" and labels, but that was reported earlier.

The skip link is broken here (and other non-home pages) too - http://wave.webaim.org/report?url=http%3A%2F%2Fwet.openplus.ca%2Fen%2Fsearch

There's also work that can be done on form validation from - http://wet.openplus.ca/en/contact

It's an ongoing issue with D8 that we're still struggling with.  Anyone wanting to look at best practices with Drupal I can direct them.

**Comment by sylus** [comment]
Cool thanks @mgifford I will be working on those issues as well. Ideally if we can get a few more resources on this after I go through a first round I appreciate it.

We have to make sure on launch (September 17th) that we are accessible and fully compliant markup as possible. First impressions are everything.

We should all take this very seriously as a lot more eyes are going to be on this project starting end of september.

**Comment by sylus** [comment]
We now validate fully with the W3C HTML5 validator, will update the live site (wet.openplus.ca) tomorrow morning so people can validate for themselves and offer up improvements :)

Next step is improve the HTML5 metatags that was just added as per #255

@sinkinsona

**Comment by StephenOTT** [comment]
@sylus Will start testing thoroughly first thing tomorrow.

**Comment by sylus** [comment]
Marking this closed as all markup is now validated and waiting on the usability group results.
