### ISSUE TITLE
 Error message The Dublin Core Language is using the following invalid tokens: [current-page:language].

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-drupal#650]
With a fresh install I can't create a new user.  I'm getting the following error:
    Error message  - The Dublin Core Language is using the following invalid tokens: [current-page:language].

This after getting a whole lot of errors like this:
  https://drupal.org/node/1712336

The first time I tried it.  So something in the DC isn't happy with tokens.

**Comment by sylus** [comment]
Think this was fixed in recent pull. But will confirm tonight

**Comment by sylus** [comment]
Ah some of the new custom tokens I created aren't assigned to the custom token group. Know the problem now will fix tonight

**Comment by mgifford** [comment]
Thanks.

**Comment by sylus** [comment]
Fixed!

**Comment by nadinecz** [comment]
While adding a taxonomy term (on a fresh install), got the same error + one for [site-wide:creator].  

Applied the patch this morning (for language and creator....   

The language and all the other message are fixed, EXCEPT  I'm still getting the  The Dublin Core Creator is using the following invalid tokens: [site-wide:creator].   Prevents from saving the term.

Thoughts?

**Comment by sylus** [comment]
Confirmed, a very nasty bug. Priority Issue.

**Comment by sylus** [comment]
Fixed once and for all! :)

**Comment by mgifford** [comment]
Will the fix be applied with `drush updb` or will it only come into effect with a new install?

I just got it after pulling down the latest from last night and applying it.

**Comment by sylus** [comment]
It should be applied with a drush updb and drush cc all. Confirmed by testing!
